### PR TITLE
Fix sort command error

### LINKED ISSUE #237: Sort command error message incorrect
Step 1: Type `sort afnieaanaifnwanafneanaeoenaervno`

Step 2: Observe error message below
image

It states that the command format is incorrect, which is wrong.

### PR DESCRIPTION
**Pull request by papataco14**
fix sort command error message. 

closes #237

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/SortCommandParser.java [hunk 1]
```diff
@@ -1,7 +1,7 @@
 package seedu.address.logic.parser;
 
 import static java.util.Objects.requireNonNull;
-import static seedu.address.logic.Messages.MESSAGE_INVALID_COMMAND_FORMAT;
+//import static seedu.address.logic.Messages.MESSAGE_INVALID_COMMAND_FORMAT;
```
Comment (tayruxin) [inline src/main/java/seedu/address/logic/parser/SortCommandParser.java:4]: perhaps can just delete it, instead of commenting it out

**Review by tayruxin — APPROVED** [review]
LGTM
